name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1
      - name: Generate JavaDocs
        run: ./gradlew generateJavadoc

      - name: Deploy JavaDocs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          publish_branch: gh-pages
